[project]
name = "alloconda-workspace"
version = "0.0.0"
requires-python = ">=3.13"
dependencies = ["alloconda"]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "python/alloconda",
    "python/zigadd",
]

[tool.uv.sources]
alloconda = { workspace = true }
